"""Grammar constants and metadata.

This module contains all constants and metadata used by the grammar system,
separated from the types to avoid circular imports between grammar/support.py
and grammar/model_types.py.

Auto-generated grammar models.

This file was generated by imas_standard_names.grammar_codegen.generate
from imas_standard_names/grammar/specification.yml. Do not edit manually."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass

from .model_types import (
    Aggregation,
    Channel,
    ChannelQualifier,
    Component,
    Coordinate,
    GeometricBase,
    GeometryRepresentation,
    Object,
    Orbit,
    Population,
    Position,
    Process,
    Qualifier,
    Region,
    SectionPlane,
    State,
    Subject,
    Zone,
)
from .vocab_loaders import load_locus_registry, load_physical_bases


@dataclass(frozen=True)
class SegmentRule:
    identifier: str
    optional: bool
    template: str | None
    exclusive_with: tuple[str, ...]
    tokens: tuple[str, ...]


SEGMENT_TOKEN_MAP: dict[str, tuple[str, ...]] = {
    "component": tuple(member.value for member in Component),
    "coordinate": tuple(member.value for member in Coordinate),
    "section_plane": tuple(member.value for member in SectionPlane),
    "aggregation": tuple(member.value for member in Aggregation),
    "qualifier": tuple(member.value for member in Qualifier),
    "zone": tuple(member.value for member in Zone),
    "orbit": tuple(member.value for member in Orbit),
    "population": tuple(member.value for member in Population),
    "subject": tuple(member.value for member in Subject),
    "state": tuple(member.value for member in State),
    "device": tuple(member.value for member in Object),
    "channel_qualifier": tuple(member.value for member in ChannelQualifier),
    "channel": tuple(member.value for member in Channel),
    "geometry_representation": tuple(member.value for member in GeometryRepresentation),
    "geometric_base": tuple(member.value for member in GeometricBase),
    "physical_base": tuple(sorted(load_physical_bases().bases.keys())),
    "object": tuple(member.value for member in Object),
    "geometry": tuple(member.value for member in Position),
    "position": tuple(member.value for member in Position),
    "region": tuple(member.value for member in Region),
    "path": tuple(member.value for member in Position),
    "process": tuple(member.value for member in Process),
    "locus_qualifier": tuple(load_locus_registry().locus_qualifiers),
}

SEGMENT_RULES: tuple[SegmentRule, ...] = (
    SegmentRule(
        identifier="component",
        optional=True,
        template=None,
        exclusive_with=("coordinate",),
        tokens=SEGMENT_TOKEN_MAP["component"],
    ),
    SegmentRule(
        identifier="coordinate",
        optional=True,
        template=None,
        exclusive_with=("component",),
        tokens=SEGMENT_TOKEN_MAP["coordinate"],
    ),
    SegmentRule(
        identifier="section_plane",
        optional=True,
        template="{token}_plane_",
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["section_plane"],
    ),
    SegmentRule(
        identifier="aggregation",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["aggregation"],
    ),
    SegmentRule(
        identifier="qualifier",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["qualifier"],
    ),
    SegmentRule(
        identifier="zone",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["zone"],
    ),
    SegmentRule(
        identifier="orbit",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["orbit"],
    ),
    SegmentRule(
        identifier="population",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["population"],
    ),
    SegmentRule(
        identifier="subject",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["subject"],
    ),
    SegmentRule(
        identifier="state",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["state"],
    ),
    SegmentRule(
        identifier="device",
        optional=True,
        template=None,
        exclusive_with=("object",),
        tokens=SEGMENT_TOKEN_MAP["device"],
    ),
    SegmentRule(
        identifier="channel_qualifier",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["channel_qualifier"],
    ),
    SegmentRule(
        identifier="channel",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["channel"],
    ),
    SegmentRule(
        identifier="geometry_representation",
        optional=True,
        template=None,
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["geometry_representation"],
    ),
    SegmentRule(
        identifier="geometric_base",
        optional=True,
        template=None,
        exclusive_with=("physical_base",),
        tokens=SEGMENT_TOKEN_MAP["geometric_base"],
    ),
    SegmentRule(
        identifier="physical_base",
        optional=True,
        template=None,
        exclusive_with=("geometric_base",),
        tokens=SEGMENT_TOKEN_MAP["physical_base"],
    ),
    SegmentRule(
        identifier="object",
        optional=True,
        template="of_{token}",
        exclusive_with=("device",),
        tokens=SEGMENT_TOKEN_MAP["object"],
    ),
    SegmentRule(
        identifier="geometry",
        optional=True,
        template="of_{token}",
        exclusive_with=("position", "region", "path"),
        tokens=SEGMENT_TOKEN_MAP["geometry"],
    ),
    SegmentRule(
        identifier="position",
        optional=True,
        template="at_{token}",
        exclusive_with=("geometry", "region", "path"),
        tokens=SEGMENT_TOKEN_MAP["position"],
    ),
    SegmentRule(
        identifier="region",
        optional=True,
        template="over_{token}",
        exclusive_with=("geometry", "position", "path"),
        tokens=SEGMENT_TOKEN_MAP["region"],
    ),
    SegmentRule(
        identifier="path",
        optional=True,
        template="along_{token}",
        exclusive_with=("geometry", "position", "region"),
        tokens=SEGMENT_TOKEN_MAP["path"],
    ),
    SegmentRule(
        identifier="process",
        optional=True,
        template="due_to_{token}",
        exclusive_with=(),
        tokens=SEGMENT_TOKEN_MAP["process"],
    ),
)

SEGMENT_ORDER: tuple[str, ...] = (
    "component",
    "coordinate",
    "section_plane",
    "aggregation",
    "qualifier",
    "zone",
    "orbit",
    "population",
    "subject",
    "state",
    "device",
    "channel_qualifier",
    "channel",
    "geometry_representation",
    "geometric_base",
    "physical_base",
    "object",
    "geometry",
    "position",
    "region",
    "path",
    "process",
)

# Base segments are at indices [14, 15] in SEGMENT_ORDER
# They mark the boundary between prefix (component, coordinate, subject) and suffix (object, geometry, position, process) segments
BASE_SEGMENT_INDICES: tuple[int, ...] = (14, 15)
BASE_SEGMENTS: tuple[str, ...] = ("geometric_base", "physical_base")
PREFIX_SEGMENTS: tuple[str, ...] = SEGMENT_ORDER[: BASE_SEGMENT_INDICES[0]]
SUFFIX_SEGMENTS: tuple[str, ...] = SEGMENT_ORDER[BASE_SEGMENT_INDICES[-1] + 1 :]
SUFFIX_SEGMENTS_REVERSED: tuple[str, ...] = tuple(reversed(SUFFIX_SEGMENTS))

SEGMENT_TEMPLATES: dict[str, str] = {
    "section_plane": "{token}_plane_",
    "object": "of_{token}",
    "geometry": "of_{token}",
    "position": "at_{token}",
    "region": "over_{token}",
    "path": "along_{token}",
    "process": "due_to_{token}",
}

SEGMENT_SEARCH_TOKEN_MAP: dict[str, tuple[str, ...]] = {
    key: tuple(sorted(tokens, key=len, reverse=True))
    for key, tokens in SEGMENT_TOKEN_MAP.items()
}
SEGMENT_PREFIX_TOKEN_MAP: Mapping[str, tuple[str, ...]] = SEGMENT_SEARCH_TOKEN_MAP
SEGMENT_SUFFIX_TOKEN_MAP: Mapping[str, tuple[str, ...]] = SEGMENT_SEARCH_TOKEN_MAP

EXCLUSIVE_SEGMENT_PAIRS: tuple[tuple[str, str], ...] = (
    ("component", "coordinate"),
    ("device", "object"),
    ("geometric_base", "physical_base"),
    ("geometry", "path"),
    ("geometry", "position"),
    ("geometry", "region"),
    ("path", "position"),
    ("path", "region"),
    ("position", "region"),
)

# Applicability: when to create standard names
APPLICABILITY_INCLUDE: tuple[str, ...] = (
    "Conceptual definitions: plasma regions, boundaries, reference surfaces,  and operational modes",
    "Physical quantities: measurements, diagnostic signals, and derived calculations",
    "Geometric quantities: spatial locations, shapes, dimensions, and extents",
    "Hardware properties: physical characteristics and configuration parameters",
    "Coordinate systems: time, spatial coordinates, and flux coordinates",
)
APPLICABILITY_EXCLUDE: tuple[str, ...] = (
    "Facility-specific identifiers and labels  (paths like */name, */identifier, */label)",
    "Type enumeration indices (paths like */type/index)",
    "Code provenance metadata (paths like */code/*, */ids_properties/*)",
)
APPLICABILITY_RATIONALE: str = "Standard names cover physical quantities with standardizable meaning and units,  as well as conceptual definitions that establish shared understanding of plasma regions,  boundaries, and reference coordinates across codes and diagnostics.\n"


# Generic physical bases that require qualification
# These physical_base tokens cannot stand alone and must have
# subject, device, object, position, or geometry qualification
GENERIC_PHYSICAL_BASES: tuple[str, ...] = (
    "area",
    "current",
    "energy",
    "flux",
    "frequency",
    "number_density",
    "power",
    "pressure",
    "temperature",
    "velocity",
    "voltage",
    "volume",
    "coefficient",
    "count",
    "distribution",
    "factor",
    "field_strength",
    "flag",
    "flow",
    "index",
    "multiplicity",
    "parameter",
    "potential",
    "rate",
    "residual",
    "size",
    "source",
    "weight",
)


# Unary transformation tokens that modify a physical base
# These are prefixed to the physical_base: e.g. square_of_temperature
# Empty tuple when 'transformations' vocabulary is absent (use operators.yml)
TRANSFORMATION_TOKENS: tuple[str, ...] = (
    "accumulated",
    "cumulative",
    "cumulative_inside_flux_surface",
    "derivative",
    "derivative_with_respect_to",
    "flux_surface_averaged",
    "gradient",
    "inverse",
    "line_averaged",
    "line_integrated",
    "logarithm",
    "magnitude",
    "maximum",
    "maximum_over_flux_surface",
    "minimum",
    "minimum_over_flux_surface",
    "normalized",
    "per_toroidal_mode",
    "per_poloidal_mode",
    "per_toroidal_and_poloidal_mode_number",
    "perturbed",
    "radial_derivative",
    "root_mean_square",
    "second_derivative",
    "second_radial_derivative",
    "square",
    "surface_integrated",
    "change_in",
    "time_averaged",
    "time_derivative",
    "variation",
    "volume_averaged",
    "volume_integrated",
    "upper_uncertainty",
    "lower_uncertainty",
    "uncertainty_index",
    "amplitude",
    "real_part",
    "imaginary_part",
    "bessel_0",
    "bessel_1",
    "constraint_exact_flag",
    "fourier_coefficient",
    "gyroaveraged",
    "moment",
    "per_solid_angle",
    "reference_waveform",
    "waveform",
)


# Mode / Fourier / spectral decomposition tokens prefixed to the
# physical_base between transformation and base:
# e.g. fourier_coefficient_of_magnetic_field, n_equals_1_magnetic_field
# Empty tuple when 'decomposition' vocabulary is absent (use operators.yml)
DECOMPOSITION_TOKENS: tuple[str, ...] = (
    "accumulated",
    "cumulative",
    "cumulative_inside_flux_surface",
    "derivative",
    "derivative_with_respect_to",
    "flux_surface_averaged",
    "gradient",
    "inverse",
    "line_averaged",
    "line_integrated",
    "logarithm",
    "magnitude",
    "maximum",
    "maximum_over_flux_surface",
    "minimum",
    "minimum_over_flux_surface",
    "normalized",
    "per_toroidal_mode",
    "per_poloidal_mode",
    "per_toroidal_and_poloidal_mode_number",
    "perturbed",
    "radial_derivative",
    "root_mean_square",
    "second_derivative",
    "second_radial_derivative",
    "square",
    "surface_integrated",
    "change_in",
    "time_averaged",
    "time_derivative",
    "variation",
    "volume_averaged",
    "volume_integrated",
    "upper_uncertainty",
    "lower_uncertainty",
    "uncertainty_index",
    "amplitude",
    "real_part",
    "imaginary_part",
    "bessel_0",
    "bessel_1",
    "constraint_exact_flag",
    "fourier_coefficient",
    "gyroaveraged",
    "moment",
    "per_solid_angle",
    "reference_waveform",
    "waveform",
)


# Binary operator tokens that combine two physical bases
BINARY_OPERATOR_TOKENS: tuple[str, ...] = (
    "product_of",
    "ratio_of",
    "difference_of",
)


# Maps each binary operator to its connector word
# Symmetric operators use 'and'; asymmetric (ratio) uses 'to'
BINARY_OPERATOR_CONNECTORS: dict[str, str] = {
    "product_of": "and",
    "ratio_of": "to",
    "difference_of": "and",
}

__all__ = [
    "SegmentRule",
    "SEGMENT_TOKEN_MAP",
    "SEGMENT_RULES",
    "SEGMENT_ORDER",
    "BASE_SEGMENT_INDICES",
    "BASE_SEGMENTS",
    "PREFIX_SEGMENTS",
    "SUFFIX_SEGMENTS",
    "SUFFIX_SEGMENTS_REVERSED",
    "SEGMENT_TEMPLATES",
    "SEGMENT_SEARCH_TOKEN_MAP",
    "SEGMENT_PREFIX_TOKEN_MAP",
    "SEGMENT_SUFFIX_TOKEN_MAP",
    "EXCLUSIVE_SEGMENT_PAIRS",
    "APPLICABILITY_INCLUDE",
    "APPLICABILITY_EXCLUDE",
    "APPLICABILITY_RATIONALE",
    "GENERIC_PHYSICAL_BASES",
    "TRANSFORMATION_TOKENS",
    "DECOMPOSITION_TOKENS",
    "BINARY_OPERATOR_TOKENS",
    "BINARY_OPERATOR_CONNECTORS",
]
