on:
  issues:
    types: [labeled]

jobs:

  parse-issue:
    uses: ./.github/workflows/parse-issue.yml

  merge-issue:
    if: ${{ github.event.label.name == 'merge' }}
    runs-on: ubuntu-latest
    needs: parse-issue

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install imas-standard-names
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Update
        id: update
        run: |
          echo ${{ needs.parse-issue.outputs.submission }} > submission.json
          echo "result=$(update_standardnames standardnames.yml submission.json)" >> $GITHUB_OUTPUT

      - name: Validate
        id: validate
        run: |
          echo "succsess=contains(${{ steps.update.outputs.result }}, 'appended to')" >> $GITHUB_OUTPUT
      
      - name: Remove merge label
        if: ${{ !steps.validate.outputs.success }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: gh issue edit $ISSUE_URL --remove-label "merge"

      - name: Comment on issue
        if: ${{ !steps.validate.outputs.success }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo ${{ steps.update.outputs.result }} > error_message.md
          gh issue comment $ISSUE_URL --body-file error_message.md

      # - run: node submission.js

      # - run: yarn
      
      # - run: node ./update.js
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - run: node ./generate-readme.js

      # - run: |
      #       git config user.email "github@stefanbuck.com"
      #       git config user.name "Stefan Buck"
      #       git add README.md data.json
      #       git diff-index --quiet HEAD || git commit -m "Add new list item"

      # - run: git push

      - name: Close issue
        if: ${{ steps.validate.outputs.success }}
        uses: peter-evans/close-issue@v1
        with:
          comment: Merged **${{ needs.parse-issue.outputs.standard-name }}** with <a href="../">standardnames.yml</a>.
