on:
  issues:
    types: [labeled]

jobs:

  parse-issue:
    uses: ./.github/workflows/parse-issue.yml

  label-issue:
    uses: ./.github/workflows/label-issue.yml

  merge-issue:
    if: ${{ github.event.label.name == 'merge' }}
    runs-on: ubuntu-latest
    needs: [parse-issue, label-issue]

    steps:

      # - run: node submission.js

      # - run: yarn
      
      # - run: node ./update.js
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - run: node ./generate-readme.js

      # - run: |
      #       git config user.email "github@stefanbuck.com"
      #       git config user.name "Stefan Buck"
      #       git add README.md data.json
      #       git diff-index --quiet HEAD || git commit -m "Add new list item"

      # - run: git push

      - name: Close issue
        if: contains(${{ needs.label-issue.outputs.update }}, 'Success')
        uses: peter-evans/close-issue@v1
        with:
          comment: Merged **${{ needs.parse-issue.outputs.standard-name }}** with <a href="../">standardnames.yml</a>.
