on:
  workflow_call:
    outputs:
      standard-name:
        description: 'Proposed Standard Name.'
        value: ${{ jobs.parse-issue.outputs.standard-name }}
      priority:
        description: 'Priority label to be added to the issue.'
        value: ${{ jobs.parse-issue.outputs.priority }}
      overwrite:
        description: 'Overwrite checkbox status.'
        value: ${{ jobs.parse-issue.outputs.overwrite == 'Overwrite' }}

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    outputs:
      standard-name: ${{ steps.issue-parser.outputs.issueparser_name }}
      priority: ${{ steps.issue-parser.outputs.issueparser_priority }}
      overwrite: ${{ steps.issue-parser.outputs.issueparser_overwrite }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: stefanbuck/github-issue-parser@v3
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/standard-name.yml

    - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > submission.json